from datetime import datetime

from models import Document


class ComplianceSummarizer:

    def generate(self, document: Document) -> Document:

        report = f"""

Generated:
{datetime.now().strftime("%d-%m-%Y %H:%M")}

---


- Name: {document.original_name}
- Type: {document.extension}

---


- Characters: {document.character_count}
- Words: {document.word_count}
- Lines: {document.line_count}

---


- Risk Score: {document.risk_score}
- Compliance Score: {document.compliance_score}
- Risk Level: {document.risk_level}

---


Detected Entities: {len(document.entities)}

"""

        for entity in document.entities:
            report += (
                f"- {entity.category}: "
                f"{entity.value} "
                f"({entity.method})\n"
            )

        report += "\n---\n\n## Recommendations\n\n"

        for recommendation in document.recommendations:
            report += f"- {recommendation}\n"

        report += "\n---\nGenerated by MSentinel AI"

        document.report_markdown = report

        return document