from datetime import datetime
from models import Document

class ComplianceSummarizer:
    def generate(self, document: Document) -> Document:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        risk_color = "red" if document.risk_score >= 50 else ("orange" if document.risk_score >= 20 else "green")
        
        report = f"""# MSentinel AI Compliance Report

**Generated:** {timestamp}  
**Document Security Clearance Audit**

---

## 1. Executive Summary
The document **{document.original_name}** has undergone multi-layered deep inspection scanning. 
The analysis indicates an overall **{document.risk_level.upper()}** risk profile. 
Immediate security actions are recommended for identified vulnerabilities to achieve policy alignment.

* **Overall Risk Score:** {document.risk_score} / 100
* **Compliance Rating:** {document.compliance_score} %
* **Clearance Status:** {"⚠️ Action Required" if document.risk_score >= 20 else "✅ Compliant"}

---

## 2. Document Profile Summary
* **Filename:** {document.original_name}
* **Extension:** {document.extension.upper()}
* **Characters:** {document.character_count:,}
* **Words:** {document.word_count:,}
* **Lines:** {document.line_count:,}
* **OCR Conversion:** {"Yes" if document.ocr_used else "No"}

---

## 3. Sensitive Data Summary & Findings
A total of **{len(document.entities)}** sensitive data elements were detected.

| Category | Detection Method | Confidence | Risk Weight | Page | Value |
| :--- | :--- | :--- | :--- | :--- | :--- |
"""

        if not document.entities:
            report += "| None | N/A | N/A | N/A | N/A | No sensitive data detected. |\n"
        else:
            for entity in document.entities:
                report += f"| {entity.category} | {entity.method} | {entity.confidence:.2f} | {entity.risk_weight} | {getattr(entity, 'page', 1)} | `{entity.value}` |\n"

        report += """
---

## 4. Security Risks & Compliance Gaps
* **Exposure Level:** The presence of unmasked high-impact variables (e.g. credentials, identity cards) represents compliance gaps under data protection guidelines (such as GDPR, HIPAA, SOC2, or local regulatory laws).
* **Vulnerability Analysis:** The current risk level of **{0}** requires that all matching data items be masked prior to external transit.

---

## 5. Actionable Recommendations & Priority Actions
""".format(document.risk_level)

        if not document.recommendations:
            report += "* **No Actions Required:** The document contains no recognizable sensitive items.\n"
        else:
            report += "### Immediate Priority Actions:\n"
            for recommendation in document.recommendations:
                report += f"- [ ] **Vulnerability Fix:** {recommendation}\n"
                
            report += "\n### Standard Guidance Guidelines:\n"
            report += "- Rotate any exposed API tokens or credential keys immediately.\n"
            report += "- Review sharing permissions for this document to prevent unauthorized leakage.\n"

        report += "\n---\n*Report generated by MSentinel AI Document Security & Compliance Platform.*"
        
        document.report_markdown = report
        return document